Fix unit tests when run on a computer not having umask set to 0022
If umask was set to, for example, 0027 some tests failed because the
file mode of the created file was not what was expected.

One of the failing tests:

  ======================================================================
  FAIL: test_open_mode_windows (tests.fake_os_test.FakeOsModuleLowLevelFileOpTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/code/pyfakefs/tests/fake_os_test.py", line 3499, in test_open_mode_windows
      self.assertEqual(0o100666, stat0.st_mode)
  AssertionError: 33206 != 33202

You can reproduce the issue (on Linux) by checking out older version and running
  umask 0027
  python -m tests.all_tests