Remove @DeprecationWarning as it isn't a decorator
`tearDownPyfakefs` is a no-op legacy API, it was given @DeprecationWarning as a decorator... which broke it rather than making it a no-op callable as that isn't a decorator.

This fixes:

```
    self.tearDownPyfakefs()
TypeError: 'DeprecationWarning' object is not callable
```

in code updating to a modern pyfakefs that still calls it.